<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE partido[
<!ELEMENT partido (fecha,hora,equipos,acciones)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT equipos (equipo,equipo)>
<!ELEMENT equipo (jugadores)>
<!ELEMENT equipo equipo ID #REQUIRED tipo (L|V) #REQUIRED>
<!ELEMENT jugadores (jugador+)>
<!ELEMENT jugador EMPTY>
<!ATTLIST jugador nombre ID #REQUIRED dorsal CDATA #REQUIRED posicion (portero|defensa|delantero|centro) #IMPLITED>
<!ELEMENT acciones (accion*)> <!-- considereamos que puede haber un partido que no tenga accion-->
<!ELEMENT accion (minuto, equipo, jugador)>
<!ELEMENT accion tipo (GOL|TR|TA|FJ|Penalti) #REQUIRED>
 <!ELEMENT minuto (#PCDATA)>
 <!ELEMENT equipo (#PCDATA)>
 <!ELEMENT jugador (#PCDATA)>
]
>
	<fecha>2024-01-01</fecha>
	<hora>17:00</hora>
	<equipos>
		<equipo tipo="L" nombre="RM">
			<jugadores>
				<jugador nombre="Belinghan" dorsal="5" posicion="centro"/>
				<jugador nombre="Vini" dorsal="7" posicion="delantero"/>
			</jugadores>
		</equipo>
		<equipo tipo="V" nombre="Barcelona">
			<jugadores>
				<jugador nombre="Gabi" dorsal="6" posicion="centro"/>
				<jugador nombre="Pedri" dorsal="8" posicion="Medio-Centro"/>
			</jugadores>
		</equipo>
	</equipos>
	<acciones>
		<accion tipo="G">
			<minuto>6</minuto>
			<equipo>RM</equipo>
			<jugador>5</jugador>
		</accion>
	</acciones>
</partido>
