=== cdsanchezc01/Lenguaje_Marca/u5/XML_Schema/Examen0605/biblioteca.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="libros" minOccurs="1"/>
                <xs:element ref="socio" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="libros">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="libro" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="libro"> <!-- Error atribute-->
        <xs:complexType> <!-- acuerdate como se define lo hemos hecho element y eso -->
                    <xs:attribute name="isbn" type="xs:string" use="required"/>
                    <xs:attribute name="ejemplares" type="xs:int" use="required"/>
                    <xs:attribute name="editorial" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="socio">
        <xs:complexType>
            <xs:choice>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="apellidos" type="xs:string"/>
                <xs:element ref="telefonos" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="prestamos" minOccurs="1" maxOccurs="unbounded"/>
            </xs:choice>
                <xs:attribute name="dni" type="xs:string" use="required"/>
                <xs:attribute name="fechaSancion" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="telefonos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="telefono">
                    <xs:complexType>
                        <xs:attribute name="tipo" type="xs:string" use="required"/>
                        <xs:attribute name="numero" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
   <xs:element name="prestamos">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="prestamo">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="fecha" type="xs:string"/>
                        <xs:element name="isbn" type="xs:string"/>
                        <xs:element name="fecha_devolucion" type="xs:string"/>
                        <xs:element name="fecha" type="xs:string"/>
                   </xs:sequence>
                    <xs:attribute name="codigo" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
   </xs:element>
   













</xs:schema>

=== cdsanchezc01/Lenguaje_Marca/u5/XML_Schema/Examen0605/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="biblioteca.xsd">
	<libros>
		<libro isbn="l1" ejemplares="3" editorial="http://www.anaya.com">Don Quijote de la Mancha</libro>
		<libro isbn="l2" ejemplares="2" editorial="http://www.sm.com">La familia de Pascual Duarte</libro>
		<libro isbn="l3" ejemplares="6" editorial="http://www.santillana.com">El lazarillo de Tormes</libro>
	</libros>
	<socio dni="11111111A" fechaSancion="2024-06-01">
		<nombre>Andrés</nombre>
		<apellidos>Santos</apellidos>
		<telefonos>
			<telefono tipo="F" numero="959 232 323"/>
			<telefono tipo="M" numero="711 232 323"/>
			<telefono tipo="M" numero="811 232 323"/>
		</telefonos>
		<prestamos>
			<prestamo codigo="P1">
				<fecha>2012-05-01</fecha>
				<isbn>l1</isbn>
				<fecha_devolucion>2012-05-15</fecha_devolucion>
			</prestamo>
			<prestamo codigo="P5">
				<isbn>l3</isbn>
				<fecha>2024-05-10</fecha>
			</prestamo>
		</prestamos>
	</socio>
	<socio dni="22222222B">
		<nombre>Alice</nombre>
		<apellidos>Williams</apellidos>
		<telefonos>
			<telefono tipo="M" numero="822 232 323"/>
		</telefonos>
		<prestamos>
			<prestamo codigo="P2">
				<isbn>l2</isbn>
				<fecha>2024-04-01</fecha>
				<fecha_devolucion>2024-04-15</fecha_devolucion>
			</prestamo>
			<prestamo codigo="P3">
				<isbn>l1</isbn>
				<fecha>2024-05-01</fecha>
				<fecha_devolucion>2024-05-15</fecha_devolucion>
			</prestamo>
		</prestamos>
	</socio>
	<socio dni="33333333C">
		<nombre>Ana</nombre>
		<apellidos>Torroja</apellidos>
		<telefonos>
			<telefono tipo="F" numero="927 333 323"/>
		</telefonos>
	</socio>
</biblioteca>
