=== cdsanchezc01/Lenguaje_Marca/Recu3005/Museo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="museo">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="contacto"/>
                <xs:element ref="maquinas"/>
                <xs:element name="patrocinador" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="pais" type="xs:string" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="contacto"> <!-- falta definir numero veces-->
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="telefono" maxOccurs="unbounded"/>
                <xs:element name="email" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="telefono">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="pais" type="xs:string" use="optional"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="maquinas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="maquina" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="maquina">
        <xs:complexType>
            <xs:all>
                <xs:element name="fabricante" type="xs:string"/>
                <xs:element name="anio" type="tipoAnio" minOccurs="0"/>
                <xs:element name="foto" type="xs:string"/>
                <xs:element name="modelo" type="xs:string"/>
                <xs:element ref="adquisicion" minOccurs="0"/>
            </xs:all>
            <xs:attribute name="codigo" type="tipoCod" use="required"/>
            <xs:attribute name="tipo" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="adquisicion">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="compra"/>
                <xs:element name="donacion" type="tipoCompra"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="compra">
        <xs:complexType>
            <xs:attribute name="moneda" type="xs:string" use="required"/>
            <xs:attribute name="importe" type="xs:double" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="tipoCod">
        <xs:restriction base="xs:ID">
            <xs:pattern value="[M][0-9]{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoAnio">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="1850"/>
            <xs:maxExclusive value="1999"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoCompra">
		<xs:restriction base="xs:string">
			<xs:enumeration value="donacion"/>
			<xs:enumeration value="compra"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== cdsanchezc01/Lenguaje_Marca/Recu3005/MuseoAlumnos.xml
<?xml version="1.0" encoding="UTF-8"?>
<museo  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Museo.xsd">
    <!-- Información de contacto del museo -->
    <contacto>
        <telefono pais="ESP">987 654 321</telefono>
		<telefono>927 111 222</telefono>
        <email>info@museodecomputacion.com</email>
		<email>admin@museodecomputacion.com</email>
    </contacto>

    <!-- Lista de máquinas expuestas -->
    <maquinas>
		<maquina codigo="M001" tipo="PC">
            <fabricante>Atari</fabricante>
            <anio>1979</anio>
			<foto>m001.png</foto>
            <modelo>Atari 400</modelo>
        </maquina>
        <maquina codigo="M002" tipo="IMPR">
			<adquisicion>
				<compra moneda="EUR" importe="1.50"/>
			</adquisicion>
            <fabricante>HP</fabricante>
            <modelo>HP LaserJet</modelo>
			<foto>m002.png</foto>
        </maquina>
		<maquina codigo="M003" tipo="PC">
			<modelo>Commodore 64</modelo>
            <fabricante>Commodore</fabricante>
            <anio>1982</anio>
			<adquisicion>
				<compra moneda="EUR" importe="600.50"/>
			</adquisicion>
			<foto>m003.png</foto>
        </maquina>
        <maquina codigo="M004" tipo="PC">
            <fabricante>Sinclair</fabricante>
            <modelo>Sinclair ZX Spectrum</modelo>
			<foto>m004.png</foto>
			<adquisicion>
				<donacion>Citröen-Vigo</donacion>
			</adquisicion >
        </maquina>
        <maquina codigo="M005" tipo="CALC" >
			<anio>1976</anio>
            <modelo>TI-30</modelo>
            <fabricante>Texas Instruments</fabricante>
			<adquisicion>
				<donacion>Universidad de Extremadura</donacion>
			</adquisicion >
			<foto>m005.png</foto>
        </maquina>
    </maquinas>

    <!-- Patrocinadores -->
	<patrocinador pais="ESP">Universidad de Extremadura</patrocinador>
	<patrocinador pais="USA">Instituto Tecnológico de Massachusetts (MIT)</patrocinador>
	<patrocinador pais="UK">Universidad de Cambridge</patrocinador>
	<patrocinador pais="ESP">IBM Spain</patrocinador>
</museo>
